name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MOD_PATH: $HOME/.vmodules/vel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - uses: actions/checkout@v4
        with:
          path: vel
      - name: Setup vel mod
        run: mv vel ${{ env.MOD_PATH }}
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Run Test
        run: v test vel/vel_test.v